# Generated by Django 4.2.5 on 2023-09-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_facultad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('programa_id', models.IntegerField(primary_key=True, serialize=False)),
                ('facultad_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('cod_programa', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
